name: Build executable

jobs:
  build:
    runs-on: windows-latest

    needs: [formatting]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          pip install uv

      - name: Sync dependencies with uv
        run: |
          uv sync --all-extras --dev

      - name: Build with PyInstaller
        run: |
          uv run pyinstaller HLA-tool.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/**
